### ISSUE TITLE
Unpositioned graph output seems wrong on Master after PR #20 and PR#21

### ISSUE THREAD

**Issue by ombhilare999** [UniversalGRAMM/UGRAMM#22]
HI @HamasWaqar ,

On MASTER branch, do you know why `unpositioned_dot_output.png` and `unpositioned_dot_output.dot` stopped working after PR #20 and PR #21? They were working fine after PR #19. I’m also investigating this, and I’ll update here if I find anything.

**Comment by HamasWaqar** [comment]
@ombhilare999 could you explain more what the issue is?

**Comment by HamasWaqar** [comment]
Cause, I just ran tests on both `locking_new` and `add_all_benchmarks` branches that were pushed on the two PR and the output dot file was working. I even checked the correctness of the output also.

**Comment by HamasWaqar** [comment]
FYI, PR 21 changes only affected some of the scripts I created plus adding the remaining RIKEN benchmarks. PR 20 had changes related to UGRAMM execution but that did not mess with the output dot file.

**Comment by ombhilare999** [comment]
Hi Hamas,

Right now, in master, in the unpositioned graph the connection between blocks were missing as you can see:

https://github.com/UniversalGRAMM/UGRAMM/blob/master/unpositioned_dot_output.png

I have corrected this in PR #23.
